[package]
name = "filt"
version = "0.1.0"
authors = ["akakou <s16003@tokyo.kosen-ac.jp>"]

[dependencies]
router = "*"
config = "0.9"
hyper-native-tls = "0.2.4"

[dependencies.iron]
version = "*"

[dependencies.bodyparser]
git = "https://github.com/iron/body-parser.git"
