[package]
name = "filt"
version = "0.1.0"
authors = ["akakou <s16003@tokyo.kosen-ac.jp>"]

[dependencies]
router = "*"

[dependencies.iron]
version = "*"

[dependencies.bodyparser]
git = "https://github.com/iron/body-parser.git"
